// Initial calendar data with all games, promos, events, and player birthdays
export const initialCalendarItems = [
  // February 2026 - Spring Training Games
  { id: 1, date: '2026-02-21', type: 'home', title: 'vs LAD', assignees: [], status: 'planned', notes: '12:10 PM - Angel Stadium', links: '' },
  { id: 2, date: '2026-02-22', type: 'away', title: '@ ARI', assignees: [], status: 'planned', notes: '01:00 AM - Salt River Fields at Talking Stick', links: '' },
  { id: 3, date: '2026-02-23', type: 'home', title: 'vs TEX', assignees: [], status: 'planned', notes: '12:10 PM - Angel Stadium', links: '' },
  { id: 4, date: '2026-02-24', type: 'home', title: 'vs SF', assignees: [], status: 'planned', notes: '12:10 PM - Angel Stadium', links: '' },
  { id: 5, date: '2026-02-24', type: 'away', title: '@ COL', assignees: [], status: 'planned', notes: '12:10 PM - Salt River Fields at Talking Stick', links: '' },
  { id: 6, date: '2026-02-25', type: 'away', title: '@ SD', assignees: [], status: 'planned', notes: '12:10 PM - Peoria Sports Complex', links: '' },
  { id: 7, date: '2026-02-26', type: 'home', title: 'vs CHC', assignees: [], status: 'planned', notes: '12:10 PM - Angel Stadium', links: '' },
  { id: 8, date: '2026-02-27', type: 'away', title: '@ CIN', assignees: [], status: 'planned', notes: '01:00 AM - Goodyear Ballpark', links: '' },
  { id: 9, date: '2026-02-28', type: 'home', title: 'vs ARI', assignees: [], status: 'planned', notes: '12:10 PM - Angel Stadium', links: '' },
  
  // March 2026
  { id: 10, date: '2026-03-01', type: 'away', title: '@ LAD', assignees: [], status: 'planned', notes: '12:05 PM - Camelback Ranch', links: '' },
  { id: 11, date: '2026-03-02', type: 'home', title: 'vs KC', assignees: [], status: 'planned', notes: '12:10 PM - Angel Stadium', links: '' },
  { id: 12, date: '2026-03-03', type: 'away', title: '@ SEA', assignees: [], status: 'planned', notes: '12:10 PM - Peoria Sports Complex', links: '' },
  { id: 13, date: '2026-03-04', type: 'home', title: 'vs ITA', assignees: [], status: 'planned', notes: '12:10 PM - Angel Stadium', links: '' },
  { id: 14, date: '2026-03-05', type: 'home', title: 'vs OAK', assignees: [], status: 'planned', notes: '12:10 PM - Angel Stadium', links: '' },
  { id: 15, date: '2026-03-06', type: 'away', title: '@ CLE', assignees: [], status: 'planned', notes: '01:00 AM - Goodyear Ballpark', links: '' },
  { id: 16, date: '2026-03-07', type: 'home', title: 'vs MIL', assignees: [], status: 'planned', notes: '12:10 PM - Angel Stadium', links: '' },
  { id: 17, date: '2026-03-07', type: 'away', title: '@ OAK', assignees: [], status: 'planned', notes: '01:05 PM - Hohokam Stadium', links: '' },
  { id: 18, date: '2026-03-08', type: 'away', title: '@ TEX', assignees: [], status: 'planned', notes: '01:05 PM - Surprise Stadium', links: '' },
  { id: 19, date: '2026-03-08', type: 'away', title: '@ OAK', assignees: [], status: 'planned', notes: '01:05 PM - Hohokam Stadium', links: '' },
  { id: 20, date: '2026-03-09', type: 'away', title: '@ SF', assignees: [], status: 'planned', notes: '01:05 PM - Scottsdale Stadium', links: '' },
  { id: 21, date: '2026-03-10', type: 'home', title: 'vs SD', assignees: [], status: 'planned', notes: '01:10 PM - Angel Stadium', links: '' },
  { id: 22, date: '2026-03-11', type: 'away', title: '@ CWS', assignees: [], status: 'planned', notes: '01:05 PM - Camelback Ranch', links: '' },
  { id: 23, date: '2026-03-13', type: 'home', title: 'vs CLE', assignees: [], status: 'planned', notes: '01:10 PM - Angel Stadium', links: '' },
  { id: 24, date: '2026-03-14', type: 'home', title: 'vs SEA', assignees: [], status: 'planned', notes: '01:10 PM - Angel Stadium', links: '' },
  { id: 25, date: '2026-03-15', type: 'home', title: 'vs COL', assignees: [], status: 'planned', notes: '01:10 PM - Angel Stadium', links: '' },
  { id: 26, date: '2026-03-16', type: 'away', title: '@ OAK', assignees: [], status: 'planned', notes: '01:05 PM - Hohokam Stadium', links: '' },
  { id: 27, date: '2026-03-17', type: 'away', title: '@ CHC', assignees: [], status: 'planned', notes: '06:05 PM - Sloan Park', links: '' },
  { id: 28, date: '2026-03-18', type: 'home', title: 'vs CIN', assignees: [], status: 'planned', notes: '01:10 PM - Angel Stadium', links: '' },
  { id: 29, date: '2026-03-18', type: 'away', title: '@ MIL', assignees: [], status: 'planned', notes: '01:10 PM - American Family Fields of Phoenix', links: '' },
  { id: 30, date: '2026-03-19', type: 'away', title: '@ KC', assignees: [], status: 'planned', notes: '01:05 PM - Surprise Stadium', links: '' },
  { id: 31, date: '2026-03-20', type: 'home', title: 'vs CWS', assignees: [], status: 'planned', notes: '12:10 PM - Angel Stadium', links: '' },
  { id: 32, date: '2026-03-22', type: 'home', title: 'vs LAD', assignees: [], status: 'planned', notes: '06:05 PM - Angel Stadium', links: '' },
  { id: 33, date: '2026-03-23', type: 'away', title: '@ LAD', assignees: [], status: 'planned', notes: '01:00 AM - Camelback Ranch', links: '' },
  { id: 34, date: '2026-03-24', type: 'away', title: '@ LAD', assignees: [], status: 'planned', notes: '01:00 AM - Camelback Ranch', links: '' },
  { id: 35, date: '2026-03-26', type: 'away', title: '@ HOU', assignees: [], status: 'planned', notes: '01:00 AM - Minute Maid Park', links: '' },
  { id: 36, date: '2026-03-27', type: 'away', title: '@ HOU', assignees: [], status: 'planned', notes: '01:00 AM - Minute Maid Park', links: '' },
  { id: 37, date: '2026-03-28', type: 'away', title: '@ HOU', assignees: [], status: 'planned', notes: '01:00 AM - Minute Maid Park', links: '' },
  { id: 38, date: '2026-03-29', type: 'away', title: '@ HOU', assignees: [], status: 'planned', notes: '01:00 AM - Minute Maid Park', links: '' },
  { id: 39, date: '2026-03-30', type: 'away', title: '@ CHC', assignees: [], status: 'planned', notes: '01:00 AM - Wrigley Field', links: '' },
  { id: 40, date: '2026-03-31', type: 'away', title: '@ CHC', assignees: [], status: 'planned', notes: '01:00 AM - Wrigley Field', links: '' },
  
  // April 2026
  { id: 41, date: '2026-04-01', type: 'away', title: '@ CHC', assignees: [], status: 'planned', notes: '01:00 AM - Wrigley Field', links: '' },
  { id: 42, date: '2026-04-03', type: 'home', title: 'vs SEA', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 43, date: '2026-04-04', type: 'home', title: 'vs SEA', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 44, date: '2026-04-05', type: 'home', title: 'vs SEA', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 45, date: '2026-04-06', type: 'home', title: 'vs ATL', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 46, date: '2026-04-07', type: 'home', title: 'vs ATL', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 47, date: '2026-04-08', type: 'home', title: 'vs ATL', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 48, date: '2026-04-10', type: 'away', title: '@ NYY', assignees: [], status: 'planned', notes: '04:05 PM - Yankee Stadium', links: '' },
  { id: 49, date: '2026-04-11', type: 'away', title: '@ NYY', assignees: [], status: 'planned', notes: '10:05 AM - Yankee Stadium', links: '' },
  { id: 50, date: '2026-04-12', type: 'away', title: '@ NYY', assignees: [], status: 'planned', notes: '10:35 AM - Yankee Stadium', links: '' },
  { id: 51, date: '2026-04-13', type: 'away', title: '@ TOR', assignees: [], status: 'planned', notes: '04:07 PM - Rogers Centre', links: '' },
  { id: 52, date: '2026-04-14', type: 'away', title: '@ TOR', assignees: [], status: 'planned', notes: '04:07 PM - Rogers Centre', links: '' },
  { id: 53, date: '2026-04-15', type: 'away', title: '@ TOR', assignees: [], status: 'planned', notes: '09:37 AM - Rogers Centre', links: '' },
  { id: 54, date: '2026-04-17', type: 'home', title: 'vs HOU', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 55, date: '2026-04-18', type: 'home', title: 'vs HOU', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 56, date: '2026-04-19', type: 'home', title: 'vs HOU', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 57, date: '2026-04-20', type: 'home', title: 'vs NYM', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 58, date: '2026-04-21', type: 'home', title: 'vs NYM', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 59, date: '2026-04-22', type: 'home', title: 'vs NYM', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 60, date: '2026-04-24', type: 'away', title: '@ DET', assignees: [], status: 'planned', notes: '03:40 PM - Comerica Park', links: '' },
  { id: 61, date: '2026-04-25', type: 'away', title: '@ DET', assignees: [], status: 'planned', notes: '01:10 PM - Comerica Park', links: '' },
  { id: 62, date: '2026-04-26', type: 'away', title: '@ DET', assignees: [], status: 'planned', notes: '10:40 AM - Comerica Park', links: '' },
  { id: 63, date: '2026-04-27', type: 'away', title: '@ TB', assignees: [], status: 'planned', notes: '10:10 AM - Tropicana Field', links: '' },
  { id: 64, date: '2026-04-28', type: 'away', title: '@ TB', assignees: [], status: 'planned', notes: '03:50 PM - Tropicana Field', links: '' },
  { id: 65, date: '2026-04-29', type: 'away', title: '@ TB', assignees: [], status: 'planned', notes: '03:50 PM - Tropicana Field', links: '' },
  
  // May 2026
  { id: 66, date: '2026-05-01', type: 'home', title: 'vs OAK', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 67, date: '2026-05-02', type: 'home', title: 'vs OAK', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 68, date: '2026-05-03', type: 'home', title: 'vs OAK', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 69, date: '2026-05-04', type: 'home', title: 'vs MIN', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 70, date: '2026-05-05', type: 'home', title: 'vs MIN', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 71, date: '2026-05-06', type: 'home', title: 'vs MIN', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 72, date: '2026-05-08', type: 'away', title: '@ OAK', assignees: [], status: 'planned', notes: '06:40 PM - Oakland Coliseum', links: '' },
  { id: 73, date: '2026-05-09', type: 'away', title: '@ OAK', assignees: [], status: 'planned', notes: '01:07 PM - Oakland Coliseum', links: '' },
  { id: 74, date: '2026-05-10', type: 'away', title: '@ OAK', assignees: [], status: 'planned', notes: '01:07 PM - Oakland Coliseum', links: '' },
  { id: 75, date: '2026-05-12', type: 'away', title: '@ SD', assignees: [], status: 'planned', notes: '06:40 PM - Petco Park', links: '' },
  { id: 76, date: '2026-05-13', type: 'away', title: '@ SD', assignees: [], status: 'planned', notes: '06:40 PM - Petco Park', links: '' },
  { id: 77, date: '2026-05-14', type: 'away', title: '@ SD', assignees: [], status: 'planned', notes: '12:40 PM - Petco Park', links: '' },
  { id: 78, date: '2026-05-15', type: 'home', title: 'vs TOR', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 79, date: '2026-05-16', type: 'home', title: 'vs TOR', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 80, date: '2026-05-17', type: 'home', title: 'vs TOR', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 81, date: '2026-05-18', type: 'home', title: 'vs CHC', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 82, date: '2026-05-19', type: 'home', title: 'vs CHC', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 83, date: '2026-05-20', type: 'home', title: 'vs CHC', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 84, date: '2026-05-22', type: 'away', title: '@ BOS', assignees: [], status: 'planned', notes: '04:10 PM - Fenway Park', links: '' },
  { id: 85, date: '2026-05-23', type: 'away', title: '@ BOS', assignees: [], status: 'planned', notes: '01:10 PM - Fenway Park', links: '' },
  { id: 86, date: '2026-05-24', type: 'away', title: '@ BOS', assignees: [], status: 'planned', notes: '10:35 AM - Fenway Park', links: '' },
  { id: 87, date: '2026-05-25', type: 'away', title: '@ CWS', assignees: [], status: 'planned', notes: '11:10 AM - Guaranteed Rate Field', links: '' },
  { id: 88, date: '2026-05-26', type: 'away', title: '@ CWS', assignees: [], status: 'planned', notes: '05:10 PM - Guaranteed Rate Field', links: '' },
  { id: 89, date: '2026-05-27', type: 'away', title: '@ CWS', assignees: [], status: 'planned', notes: '05:10 PM - Guaranteed Rate Field', links: '' },
  { id: 90, date: '2026-05-29', type: 'home', title: 'vs TB', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 91, date: '2026-05-30', type: 'home', title: 'vs TB', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 92, date: '2026-05-31', type: 'home', title: 'vs TB', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  
  // June 2026
  { id: 93, date: '2026-06-01', type: 'home', title: 'vs TB', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 94, date: '2026-06-02', type: 'home', title: 'vs SEA', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 95, date: '2026-06-03', type: 'home', title: 'vs SEA', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 96, date: '2026-06-04', type: 'home', title: 'vs SEA', assignees: [], status: 'planned', notes: '12:38 PM - Angel Stadium', links: '' },
  { id: 97, date: '2026-06-05', type: 'away', title: '@ ARI', assignees: [], status: 'planned', notes: '06:40 PM - Chase Field', links: '' },
  { id: 98, date: '2026-06-06', type: 'away', title: '@ ARI', assignees: [], status: 'planned', notes: '05:10 PM - Chase Field', links: '' },
  { id: 99, date: '2026-06-07', type: 'away', title: '@ ARI', assignees: [], status: 'planned', notes: '01:10 PM - Chase Field', links: '' },
  { id: 100, date: '2026-06-09', type: 'away', title: '@ PIT', assignees: [], status: 'planned', notes: '03:35 PM - PNC Park', links: '' },
  { id: 101, date: '2026-06-10', type: 'away', title: '@ PIT', assignees: [], status: 'planned', notes: '03:35 PM - PNC Park', links: '' },
  { id: 102, date: '2026-06-11', type: 'away', title: '@ PIT', assignees: [], status: 'planned', notes: '09:35 AM - PNC Park', links: '' },
  { id: 103, date: '2026-06-12', type: 'away', title: '@ WSH', assignees: [], status: 'planned', notes: '04:05 PM - Nationals Park', links: '' },
  { id: 104, date: '2026-06-13', type: 'away', title: '@ WSH', assignees: [], status: 'planned', notes: '01:05 PM - Nationals Park', links: '' },
  { id: 105, date: '2026-06-14', type: 'away', title: '@ WSH', assignees: [], status: 'planned', notes: '10:35 AM - Nationals Park', links: '' },
  { id: 106, date: '2026-06-15', type: 'home', title: 'vs LAD', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 107, date: '2026-06-16', type: 'home', title: 'vs LAD', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 108, date: '2026-06-17', type: 'home', title: 'vs LAD', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 109, date: '2026-06-19', type: 'home', title: 'vs SF', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 110, date: '2026-06-20', type: 'home', title: 'vs SF', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 111, date: '2026-06-21', type: 'home', title: 'vs SF', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 112, date: '2026-06-22', type: 'home', title: 'vs BAL', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 113, date: '2026-06-23', type: 'home', title: 'vs BAL', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 114, date: '2026-06-24', type: 'home', title: 'vs BAL', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 115, date: '2026-06-26', type: 'home', title: 'vs OAK', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 116, date: '2026-06-27', type: 'home', title: 'vs OAK', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 117, date: '2026-06-28', type: 'home', title: 'vs OAK', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 118, date: '2026-06-29', type: 'away', title: '@ SEA', assignees: [], status: 'planned', notes: '06:40 PM - T-Mobile Park', links: '' },
  { id: 119, date: '2026-06-30', type: 'away', title: '@ SEA', assignees: [], status: 'planned', notes: '06:40 PM - T-Mobile Park', links: '' },
  
  // July 2026
  { id: 120, date: '2026-07-02', type: 'away', title: '@ SEA', assignees: [], status: 'planned', notes: '06:40 PM - T-Mobile Park', links: '' },
  { id: 121, date: '2026-07-03', type: 'home', title: 'vs BOS', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 122, date: '2026-07-04', type: 'home', title: 'vs BOS', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 123, date: '2026-07-05', type: 'home', title: 'vs BOS', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 124, date: '2026-07-07', type: 'away', title: '@ TEX', assignees: [], status: 'planned', notes: '05:05 PM - Globe Life Field', links: '' },
  { id: 125, date: '2026-07-08', type: 'away', title: '@ TEX', assignees: [], status: 'planned', notes: '05:05 PM - Globe Life Field', links: '' },
  { id: 126, date: '2026-07-09', type: 'away', title: '@ TEX', assignees: [], status: 'planned', notes: '05:05 PM - Globe Life Field', links: '' },
  { id: 127, date: '2026-07-10', type: 'away', title: '@ MIN', assignees: [], status: 'planned', notes: '05:10 PM - Target Field', links: '' },
  { id: 128, date: '2026-07-11', type: 'away', title: '@ MIN', assignees: [], status: 'planned', notes: '11:10 AM - Target Field', links: '' },
  { id: 129, date: '2026-07-12', type: 'away', title: '@ MIN', assignees: [], status: 'planned', notes: '11:10 AM - Target Field', links: '' },
  { id: 130, date: '2026-07-17', type: 'home', title: 'vs DET', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 131, date: '2026-07-18', type: 'home', title: 'vs DET', assignees: [], status: 'planned', notes: '07:07 PM - Angel Stadium', links: '' },
  { id: 132, date: '2026-07-19', type: 'home', title: 'vs DET', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 133, date: '2026-07-20', type: 'home', title: 'vs STL', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 134, date: '2026-07-21', type: 'home', title: 'vs STL', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 135, date: '2026-07-22', type: 'home', title: 'vs STL', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 136, date: '2026-07-24', type: 'away', title: '@ SF', assignees: [], status: 'planned', notes: '07:15 PM - Oracle Park', links: '' },
  { id: 137, date: '2026-07-25', type: 'away', title: '@ SF', assignees: [], status: 'planned', notes: '01:00 AM - Oracle Park', links: '' },
  { id: 138, date: '2026-07-26', type: 'away', title: '@ SF', assignees: [], status: 'planned', notes: '01:05 PM - Oracle Park', links: '' },
  { id: 139, date: '2026-07-27', type: 'home', title: 'vs HOU', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 140, date: '2026-07-28', type: 'home', title: 'vs HOU', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 141, date: '2026-07-29', type: 'home', title: 'vs HOU', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 142, date: '2026-07-31', type: 'home', title: 'vs MIL', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  
  // August 2026
  { id: 143, date: '2026-08-01', type: 'home', title: 'vs MIL', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 144, date: '2026-08-02', type: 'home', title: 'vs MIL', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 145, date: '2026-08-04', type: 'away', title: '@ BAL', assignees: [], status: 'planned', notes: '03:35 PM - Camden Yards', links: '' },
  { id: 146, date: '2026-08-05', type: 'away', title: '@ BAL', assignees: [], status: 'planned', notes: '03:35 PM - Camden Yards', links: '' },
  { id: 147, date: '2026-08-06', type: 'away', title: '@ BAL', assignees: [], status: 'planned', notes: '09:35 AM - Camden Yards', links: '' },
  { id: 148, date: '2026-08-07', type: 'away', title: '@ MIA', assignees: [], status: 'planned', notes: '04:10 PM - loanDepot Park', links: '' },
  { id: 149, date: '2026-08-08', type: 'away', title: '@ MIA', assignees: [], status: 'planned', notes: '01:10 PM - loanDepot Park', links: '' },
  { id: 150, date: '2026-08-09', type: 'away', title: '@ MIA', assignees: [], status: 'planned', notes: '10:40 AM - loanDepot Park', links: '' },
  { id: 151, date: '2026-08-10', type: 'home', title: 'vs TEX', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 152, date: '2026-08-11', type: 'home', title: 'vs TEX', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 153, date: '2026-08-12', type: 'home', title: 'vs TEX', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 154, date: '2026-08-13', type: 'home', title: 'vs TEX', assignees: [], status: 'planned', notes: '07:07 PM - Angel Stadium', links: '' },
  { id: 155, date: '2026-08-14', type: 'home', title: 'vs KC', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 156, date: '2026-08-15', type: 'home', title: 'vs KC', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 157, date: '2026-08-16', type: 'home', title: 'vs KC', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 158, date: '2026-08-18', type: 'away', title: '@ HOU', assignees: [], status: 'planned', notes: '01:00 AM - Minute Maid Park', links: '' },
  { id: 159, date: '2026-08-19', type: 'away', title: '@ HOU', assignees: [], status: 'planned', notes: '01:00 AM - Minute Maid Park', links: '' },
  { id: 160, date: '2026-08-20', type: 'away', title: '@ HOU', assignees: [], status: 'planned', notes: '01:00 AM - Minute Maid Park', links: '' },
  { id: 161, date: '2026-08-21', type: 'away', title: '@ TEX', assignees: [], status: 'planned', notes: '05:05 PM - Globe Life Field', links: '' },
  { id: 162, date: '2026-08-22', type: 'away', title: '@ TEX', assignees: [], status: 'planned', notes: '04:05 PM - Globe Life Field', links: '' },
  { id: 163, date: '2026-08-23', type: 'away', title: '@ TEX', assignees: [], status: 'planned', notes: '11:35 AM - Globe Life Field', links: '' },
  { id: 164, date: '2026-08-24', type: 'home', title: 'vs CLE', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 165, date: '2026-08-25', type: 'home', title: 'vs CLE', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 166, date: '2026-08-26', type: 'home', title: 'vs CLE', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 167, date: '2026-08-28', type: 'home', title: 'vs PHI', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 168, date: '2026-08-29', type: 'home', title: 'vs PHI', assignees: [], status: 'planned', notes: '07:07 PM - Angel Stadium', links: '' },
  { id: 169, date: '2026-08-30', type: 'home', title: 'vs PHI', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 170, date: '2026-08-31', type: 'home', title: 'vs NYY', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  
  // September 2026
  { id: 171, date: '2026-09-01', type: 'home', title: 'vs NYY', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 172, date: '2026-09-02', type: 'home', title: 'vs NYY', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 173, date: '2026-09-03', type: 'home', title: 'vs NYY', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 174, date: '2026-09-04', type: 'away', title: '@ LAD', assignees: [], status: 'planned', notes: '07:10 PM - Dodger Stadium', links: '' },
  { id: 175, date: '2026-09-05', type: 'away', title: '@ LAD', assignees: [], status: 'planned', notes: '01:00 AM - Dodger Stadium', links: '' },
  { id: 176, date: '2026-09-06', type: 'away', title: '@ LAD', assignees: [], status: 'planned', notes: '01:10 PM - Dodger Stadium', links: '' },
  { id: 177, date: '2026-09-07', type: 'away', title: '@ LAD', assignees: [], status: 'planned', notes: '01:10 PM - Dodger Stadium', links: '' },
  { id: 178, date: '2026-09-08', type: 'home', title: 'vs ARI', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 179, date: '2026-09-09', type: 'home', title: 'vs ARI', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 180, date: '2026-09-10', type: 'home', title: 'vs ARI', assignees: [], status: 'planned', notes: '12:38 PM - Angel Stadium', links: '' },
  { id: 181, date: '2026-09-11', type: 'home', title: 'vs SD', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 182, date: '2026-09-12', type: 'home', title: 'vs SD', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 183, date: '2026-09-13', type: 'home', title: 'vs SD', assignees: [], status: 'planned', notes: '01:07 PM - Angel Stadium', links: '' },
  { id: 184, date: '2026-09-15', type: 'away', title: '@ SEA', assignees: [], status: 'planned', notes: '06:40 PM - T-Mobile Park', links: '' },
  { id: 185, date: '2026-09-16', type: 'away', title: '@ SEA', assignees: [], status: 'planned', notes: '06:40 PM - T-Mobile Park', links: '' },
  { id: 186, date: '2026-09-17', type: 'away', title: '@ SEA', assignees: [], status: 'planned', notes: '01:10 PM - T-Mobile Park', links: '' },
  { id: 187, date: '2026-09-18', type: 'away', title: '@ COL', assignees: [], status: 'planned', notes: '05:40 PM - Coors Field', links: '' },
  { id: 188, date: '2026-09-19', type: 'away', title: '@ COL', assignees: [], status: 'planned', notes: '05:10 PM - Coors Field', links: '' },
  { id: 189, date: '2026-09-20', type: 'away', title: '@ COL', assignees: [], status: 'planned', notes: '12:10 PM - Coors Field', links: '' },
  { id: 190, date: '2026-09-22', type: 'home', title: 'vs SEA', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 191, date: '2026-09-23', type: 'home', title: 'vs SEA', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 192, date: '2026-09-24', type: 'home', title: 'vs SEA', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 193, date: '2026-09-25', type: 'home', title: 'vs HOU', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 194, date: '2026-09-26', type: 'home', title: 'vs HOU', assignees: [], status: 'planned', notes: '06:38 PM - Angel Stadium', links: '' },
  { id: 195, date: '2026-09-27', type: 'home', title: 'vs HOU', assignees: [], status: 'planned', notes: '12:07 PM - Angel Stadium', links: '' },

  // ============================================
  // PROMOS & EVENTS (imported from CSV)
  // ============================================
  { id: 200, date: '2026-04-03', type: 'event', title: 'Home Opener', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 201, date: '2026-04-03', type: 'promo', title: 'Wall Calendar', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 202, date: '2026-04-04', type: 'event', title: 'Saturday Fireworks', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 203, date: '2026-04-07', type: 'promo', title: '400th HR Bobblehead', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 204, date: '2026-04-17', type: 'promo', title: 'Mandalorian Jersey', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 205, date: '2026-04-17', type: 'event', title: 'Star Wars Weekend', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 206, date: '2026-04-18', type: 'event', title: 'Star Wars Weekend', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 207, date: '2026-04-18', type: 'event', title: 'Saturday Fireworks', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 208, date: '2026-04-20', type: 'promo', title: 'Hockey Jersey', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 209, date: '2026-05-01', type: 'promo', title: 'Bomber Jacket', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 210, date: '2026-05-02', type: 'event', title: 'Saturday Fireworks', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 211, date: '2026-05-16', type: 'event', title: 'Saturday Fireworks', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 212, date: '2026-05-22', type: 'promo', title: 'Camo Trucker Hat', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 213, date: '2026-05-23', type: 'event', title: 'Saturday Fireworks', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 214, date: '2026-06-01', type: 'promo', title: 'City Connect Cooler', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 215, date: '2026-06-08', type: 'promo', title: 'Bobblehead', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 216, date: '2026-06-12', type: 'promo', title: 'Soccer Jersey', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 217, date: '2026-06-13', type: 'event', title: 'Saturday Fireworks', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 218, date: '2026-06-14', type: 'event', title: 'Family Sunday', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 219, date: '2026-06-26', type: 'promo', title: 'Santa Hat', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 220, date: '2026-06-26', type: 'event', title: 'Christmas in June', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 221, date: '2026-06-27', type: 'event', title: 'Christmas in June', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 222, date: '2026-06-27', type: 'event', title: 'Saturday Fireworks', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 223, date: '2026-06-28', type: 'event', title: 'Christmas in June', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 224, date: '2026-06-28', type: 'event', title: 'Family Sunday', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 225, date: '2026-07-03', type: 'promo', title: 'Patriotic Hat', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 226, date: '2026-07-04', type: 'event', title: 'Fourth of July', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 227, date: '2026-07-04', type: 'event', title: 'Saturday Fireworks', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 228, date: '2026-07-05', type: 'event', title: 'Family Sunday', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 229, date: '2026-07-17', type: 'promo', title: 'Throwback Crewneck', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 230, date: '2026-07-17', type: 'event', title: 'Throwback Week', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 231, date: '2026-07-18', type: 'event', title: 'Throwback Week', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 232, date: '2026-07-18', type: 'event', title: 'Saturday Fireworks', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 233, date: '2026-07-19', type: 'event', title: 'Throwback Week', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 234, date: '2026-07-19', type: 'event', title: 'Family Sunday', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 235, date: '2026-07-20', type: 'promo', title: 'Throwback Backpack', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 236, date: '2026-07-20', type: 'event', title: 'Throwback Week', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 237, date: '2026-07-21', type: 'event', title: 'Throwback Week', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 238, date: '2026-07-22', type: 'event', title: 'Throwback Week', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 239, date: '2026-07-27', type: 'event', title: 'Beach Week', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 240, date: '2026-07-28', type: 'event', title: 'Beach Week', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 241, date: '2026-07-29', type: 'promo', title: 'Beach Towel', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 242, date: '2026-07-29', type: 'event', title: 'Beach Week', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 243, date: '2026-07-31', type: 'promo', title: 'SpongeBob Jersey', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 244, date: '2026-07-31', type: 'event', title: 'Beach Week', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 245, date: '2026-08-01', type: 'event', title: 'Beach Week', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 246, date: '2026-08-01', type: 'event', title: 'Saturday Fireworks', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 247, date: '2026-08-02', type: 'event', title: 'Beach Week', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 248, date: '2026-08-02', type: 'event', title: 'Family Sunday', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 249, date: '2026-08-12', type: 'promo', title: 'Mickey Bobblehead', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 250, date: '2026-08-14', type: 'promo', title: 'T-Shirt', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 251, date: '2026-08-15', type: 'event', title: 'Saturday Fireworks', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 252, date: '2026-08-16', type: 'event', title: 'Family Sunday', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 253, date: '2026-08-28', type: 'promo', title: 'Bobblehead', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 254, date: '2026-08-29', type: 'event', title: 'Saturday Fireworks', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 255, date: '2026-08-30', type: 'promo', title: 'Football Jersey', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 256, date: '2026-08-30', type: 'event', title: 'Family Sunday', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 257, date: '2026-09-18', type: 'promo', title: 'Angels & Ducks Blanket', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 258, date: '2026-09-18', type: 'event', title: 'Ducks Night', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 259, date: '2026-09-19', type: 'promo', title: 'Team Photo', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 260, date: '2026-09-19', type: 'event', title: 'Fan Appreciation Night', assignees: [], status: 'planned', notes: '', links: '' },
  { id: 261, date: '2026-09-19', type: 'event', title: 'Saturday Fireworks', assignees: [], status: 'planned', notes: '', links: '' },

  // ============================================
  // PLAYER BIRTHDAYS - NEW CATEGORY
  // ============================================
  { id: 300, date: '2026-01-25', type: 'birthday', title: '🎂 Walbert Ureña', assignees: [], status: 'planned', notes: 'Pitcher', links: '' },
  { id: 301, date: '2026-01-31', type: 'birthday', title: '🎂 Zach Neto', assignees: [], status: 'planned', notes: 'Shortstop - Turns 25', links: '' },
  { id: 302, date: '2026-02-08', type: 'birthday', title: '🎂 Denzer Guzman', assignees: [], status: 'planned', notes: 'Infielder', links: '' },
  { id: 303, date: '2026-02-09', type: 'birthday', title: '🎂 Logan O\'Hoppe', assignees: [], status: 'planned', notes: 'Catcher - Turns 26', links: '' },
  { id: 304, date: '2026-02-10', type: 'birthday', title: '🎂 Travis d\'Arnaud', assignees: [], status: 'planned', notes: 'Catcher - Turns 37', links: '' },
  { id: 305, date: '2026-02-14', type: 'birthday', title: '🎂 Mitch Farris', assignees: [], status: 'planned', notes: 'Pitcher - Turns 25', links: '' },
  { id: 306, date: '2026-02-14', type: 'birthday', title: '🎂 Nolan Schanuel', assignees: [], status: 'planned', notes: 'First Baseman - Turns 24', links: '' },
  { id: 307, date: '2026-02-24', type: 'birthday', title: '🎂 Robert Stephenson', assignees: [], status: 'planned', notes: 'Pitcher - Turns 33', links: '' },
  { id: 308, date: '2026-02-25', type: 'birthday', title: '🎂 Jorge Soler', assignees: [], status: 'planned', notes: 'Outfielder - Turns 34', links: '' },
  { id: 309, date: '2026-02-28', type: 'birthday', title: '🎂 Ryan Zeferjahn', assignees: [], status: 'planned', notes: 'Pitcher - Turns 28', links: '' },
  { id: 310, date: '2026-03-19', type: 'birthday', title: '🎂 Sam Bachman', assignees: [], status: 'planned', notes: 'Pitcher - Turns 27', links: '' },
  { id: 311, date: '2026-04-08', type: 'birthday', title: '🎂 Jo Adell', assignees: [], status: 'planned', notes: 'Outfielder - Turns 27', links: '' },
  { id: 312, date: '2026-05-09', type: 'birthday', title: '🎂 Matthew Lugo', assignees: [], status: 'planned', notes: 'Infielder - Turns 27', links: '' },
  { id: 313, date: '2026-05-10', type: 'birthday', title: '🎂 Cody Laweryson', assignees: [], status: 'planned', notes: 'Pitcher - Turns 28', links: '' },
  { id: 314, date: '2026-05-18', type: 'birthday', title: '🎂 Chase Silseth', assignees: [], status: 'planned', notes: 'Pitcher - Turns 26', links: '' },
  { id: 315, date: '2026-06-06', type: 'birthday', title: '🎂 Anthony Rendon', assignees: [], status: 'planned', notes: 'Third Baseman - Turns 36', links: '' },
  { id: 316, date: '2026-06-08', type: 'birthday', title: '🎂 Victor Mederos', assignees: [], status: 'planned', notes: 'Pitcher - Turns 25', links: '' },
  { id: 317, date: '2026-06-15', type: 'birthday', title: '🎂 Oswald Peraza', assignees: [], status: 'planned', notes: 'Infielder - Turns 26', links: '' },
  { id: 318, date: '2026-06-17', type: 'birthday', title: '🎂 Yusei Kikuchi', assignees: [], status: 'planned', notes: 'Pitcher - Turns 35', links: '' },
  { id: 319, date: '2026-06-18', type: 'birthday', title: '🎂 Bryce Teodosio', assignees: [], status: 'planned', notes: 'Outfielder - Turns 27', links: '' },
  { id: 320, date: '2026-07-08', type: 'birthday', title: '🎂 Reid Detmers', assignees: [], status: 'planned', notes: 'Pitcher - Turns 27', links: '' },
  { id: 321, date: '2026-08-04', type: 'birthday', title: '🎂 Brock Burke', assignees: [], status: 'planned', notes: 'Pitcher - Turns 30', links: '' },
  { id: 322, date: '2026-08-05', type: 'birthday', title: '🎂 Ryan Johnson', assignees: [], status: 'planned', notes: 'Pitcher - Turns 24', links: '' },
  { id: 323, date: '2026-08-07', type: 'birthday', title: '🎂 Mike Trout', assignees: [], status: 'planned', notes: 'Center Fielder - Turns 35', links: '' },
  { id: 324, date: '2026-09-17', type: 'birthday', title: '🎂 Ben Joyce', assignees: [], status: 'planned', notes: 'Pitcher - Turns 26', links: '' },
  { id: 325, date: '2026-10-20', type: 'birthday', title: '🎂 José Soriano', assignees: [], status: 'planned', notes: 'Pitcher - Turns 28', links: '' },
  { id: 326, date: '2026-10-21', type: 'birthday', title: '🎂 Christian Moore', assignees: [], status: 'planned', notes: 'Infielder - Turns 24', links: '' },
  { id: 327, date: '2026-11-11', type: 'birthday', title: '🎂 Kyren Paris', assignees: [], status: 'planned', notes: 'Infielder - Turns 25', links: '' },
  { id: 328, date: '2026-11-16', type: 'birthday', title: '🎂 Grayson Rodriguez', assignees: [], status: 'planned', notes: 'Pitcher - Turns 27', links: '' },
  { id: 329, date: '2026-11-28', type: 'birthday', title: '🎂 José Fermin', assignees: [], status: 'planned', notes: 'Infielder - Turns 25', links: '' },
  { id: 330, date: '2026-12-17', type: 'birthday', title: '🎂 Caden Dana', assignees: [], status: 'planned', notes: 'Pitcher - Turns 23', links: '' },
  { id: 331, date: '2026-12-22', type: 'birthday', title: '🎂 Jack Kochanowicz', assignees: [], status: 'planned', notes: 'Pitcher - Turns 26', links: '' },
];
